# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_folder.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def __init__(self):
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(440, 183)
        Dialog.setStyleSheet("background: #151515;")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 125, 440, 37))
        self.buttonBox.setStyleSheet("background: #282828;\n"
                                     "border-radius: 11px;\n"
                                     "width: 108px;\n"
                                     "height: 37px;\n"
                                     "\n"
                                     "font-family: \'Inter\';\n"
                                     "font-style: normal;\n"
                                     "font-weight: 400;\n"
                                     "font-size: 16px;\n"
                                     "line-height: 19px;\n"
                                     "/* identical to box height, or 121% */\n"
                                     "\n"
                                     "text-align: center;\n"
                                     "\n"
                                     "color: #FFFFFF;")
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(25, 25, 391, 29))
        self.label.setStyleSheet("font-family: \'Inter\';\n"
                                 "font-style: normal;\n"
                                 "font-weight: 700;\n"
                                 "font-size: 24px;\n"
                                 "line-height: 29px;\n"
                                 "/* identical to box height */\n"
                                 "\n"
                                 "\n"
                                 "color: #FFFFFF;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(25, 75, 81, 20))
        self.label_2.setStyleSheet("font-family: \'Inter\';\n"
                                   "font-style: normal;\n"
                                   "font-weight: 400;\n"
                                   "font-size: 16px;\n"
                                   "line-height: 19px;\n"
                                   "/* identical to box height, or 121% */\n"
                                   "\n"
                                   "\n"
                                   "color: #FFFFFF;")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(120, 71, 295, 29))
        self.lineEdit.setStyleSheet("background: #282828;\n"
                                    "border-radius: 7px;\n"
                                    "font-family: \'Inter\';\n"
                                    "font-style: normal;\n"
                                    "font-weight: 300;\n"
                                    "font-size: 15px;\n"
                                    "line-height: 19px;\n"
                                    "/* identical to box height, or 129% */\n"
                                    "padding: 4px 10px;\n"
                                    "\n"
                                    "color: #FFFFFF;")
        self.lineEdit.setObjectName("lineEdit")
        self.label.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.buttonBox.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)  # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Создать папку"))
        self.label_2.setText(_translate("Dialog", "Название:"))
